openedx/frontend-lib-special-exams

package-lock.json, package.json, src/constants.js, src/data/api.js, src/data/index.js, src/data/messages/constants.js, src/data/messages/handlers.js, src/data/slice.js, src/data/thunks.js, src/exam/Exam.jsx, src/exam/ExamAPIError.jsx, src/exam/ExamWrapper.jsx, src/exam/ExamWrapper.test.jsx, src/instructions/Instructions.test.jsx, src/instructions/SubmitExamInstructions.jsx, src/instructions/SubmittedExamInstructions.jsx, src/instructions/index.jsx, src/instructions/proctored_exam/EntranceProctoredExamInstructions.jsx, src/instructions/proctored_exam/RejectedProctoredExamInstructions.jsx, src/instructions/proctored_exam/SubmitProctoredExamInstructions.jsx, src/instructions/proctored_exam/SubmittedProctoredExamInstructions.jsx, src/instructions/proctored_exam/VerificationProctoredExamInstructions.jsx, src/instructions/proctored_exam/VerifiedProctoredExamInstructions.jsx, src/instructions/proctored_exam/index.js, src/setupTest.js, src/timer/CountDownTimer.jsx, src/timer/CountDownTimer.test.jsx, src/timer/ExamTimerBlock.jsx, src/timer/TimerProvider.jsx
This PR allows user-friendly handling of exam API errors (previously the errors would just be printed in the console) and also adds support for js workers from proctoring providers
JIRA: [EDUCATOR-5791](https://openedx.atlassian.net/browse/EDUCATOR-5791) [EDUCATOR-5767](https://openedx.atlassian.net/browse/EDUCATOR-5767)
=> [BD-26][EDUCATOR-5791, EDUCATOR-5767] Add handling of exam API errors and support for js workers from provider

src/data/api.js, src/data/index.js, src/data/slice.js, src/data/thunks.js, src/exam/ExamWrapper.jsx, src/instructions/EntranceInstructions.jsx, src/instructions/ErrorInstructions.jsx, src/instructions/Instructions.test.jsx, src/instructions/SubmittedInstructions.jsx, src/instructions/VerifiedInstructions.jsx, src/instructions/index.jsx, src/instructions/onboarding_exam/ErrorOnboardingExamInstructions.jsx, src/instructions/onboarding_exam/SubmittedOnboardingExamInstructions.jsx, src/instructions/onboarding_exam/VerifiedOnboardingExamInstructions.jsx, src/instructions/onboarding_exam/index.js, src/instructions/practice_exam/ErrorPracticeExamInstructions.jsx, src/instructions/practice_exam/SubmittedPracticeExamInstructions.jsx, src/instructions/practice_exam/index.js, src/instructions/proctored_exam/EntranceProctoredExamInstructions.jsx, src/instructions/proctored_exam/ErrorProctoredExamInstructions.jsx, src/instructions/proctored_exam/ProctoredExamInstructions.test.jsx, src/instructions/proctored_exam/SubmittedProctoredExamInstructions.jsx, src/instructions/proctored_exam/VerifiedProctoredExamInstructions.jsx, src/instructions/proctored_exam/prerequisites-instructions/index.jsx, src/instructions/timed_exam/SubmittedTimedExamInstructions.jsx, src/instructions/timed_exam/index.jsx
**Description**: 
Added 'allow_proctoring_opt_out' attribute for SequenceMetadata API.
Added following instruction pages:
- Error for Practice and Onboarding
- Submitted for Practice and Onboarding
- Verified for Onboarding
Removed verification check from practice and onboarding exams, check only if exam is proctored
JIRA: https://openedx.atlassian.net/browse/EDUCATOR-5808
NOTE: should be merged after #15 with https://github.com/edx/edx-platform/pull/27836 and https://github.com/edx/frontend-app-learning/pull/485
=> [BD-26][EDUCATOR-5808] Part-2 Add additional pages for onboarding / practice exams

src/instructions/Instructions.test.jsx, src/instructions/SubmitInstructions.jsx, src/instructions/index.jsx, src/instructions/proctored_exam/ProctoredExamInstructions.test.jsx, src/instructions/proctored_exam/SubmitProctoredExamInstructions.jsx, src/instructions/timed_exam/SubmitTimedExamInstructions.jsx, src/timer/TimerProvider.jsx, src/timer/events.js
Add a condition based on which continue button should be shown on ready_to_submit page, previously it was always shown
[EDUCATOR-5827](https://openedx.atlassian.net/browse/EDUCATOR-5827)
=> [BD-26] Fix a bug with continue button when on ready_to_submit page

package-lock.json, package.json, src/constants.js, src/data/__factories__/attempt.factory.js, src/data/__factories__/exam.factory.js, src/data/__factories__/examState.factory.js, src/data/__factories__/index.js, src/data/__factories__/proctoringSettings.factory.js, src/data/__snapshots__/redux.test.jsx.snap, src/data/redux.test.jsx, src/data/slice.js, src/setupTest.js, src/utils.js
Redax test coverage
Added redux tests, exam state factories, refactored initializeTestStore in setupTest.
NOTE: should be merged after https://github.com/edx/frontend-lib-special-exams/pull/21
=> [BD-26] Redax test coverage

src/exam/ExamWrapper.test.jsx, src/instructions/proctored_exam/ProctoredExamInstructions.test.jsx, src/instructions/proctored_exam/ReadyToStartProctoredExamInstructions.jsx, src/instructions/timed_exam/StartTimedExamInstructions.jsx
Fix a bug where displayed total time allowed for the exam would not include allowance time.
JIRA: [EDUCATOR-5838](https://openedx.atlassian.net/browse/EDUCATOR-5838)
=> [BD-26] Show correct allowed exam time when allowance time is added

src/exam/Exam.jsx, src/timer/ExamTimerBlock.jsx
Fixes an oversight where you could start an exam in the legacy courseware but then enter a section in the new MFE. As a result learners are able to see our (untested/unreleased) timer component. Since the end exam button does not always work this is causing learner confusion in production. I have temporarily disabled the end exam button while we work out a formal fix.
This is actually a wider oversight because learners moving from the legacy courseware to the MFE during an exam should not have been happening in the first place. Lucky for us the timer mostly works 🎉 
https://openedx.atlassian.net/browse/CR-3842
@edx/masters-devs-cosmonauts
=> fix: temporarily remove end exam button when viewing non exam content

src/data/thunks.js
When Learner (having bad connection) clicks several times on Resume button - it works but also renders Error message describing unavailability to start the exam cause it’s already started
Jira: [EDUCATOR-5871](https://openedx.atlassian.net/browse/EDUCATOR-5871)
=> [BD-26] Error when user clicks several times on continue button.

src/constants.js, src/exam/ExamAPIError.jsx, src/instructions/Instructions.test.jsx, src/instructions/UnknownAttemptStatusError.jsx, src/instructions/index.jsx
Fix missing second_review_required status for proctored exams, which resulted in showing exam content to the student
JIRA: [EDUCATOR-5909](https://openedx.atlassian.net/browse/EDUCATOR-5909)
=> [BD-26] Add handling of second review required status for proctored exams

src/exam/ExamWrapper.jsx, src/exam/ExamWrapper.test.jsx
Staff users should be able to interact with exam content without going through the exam flow
=> feat: allow staff users to bypass exam interstitials

package.json, src/exam/Exam.jsx, src/exam/ExamWrapper.jsx, src/exam/ExamWrapper.test.jsx
[MST-944](https://openedx.atlassian.net/browse/MST-944)
If a staff user is masquerading as a specific learner, they should be able to view exam content regardless of the learner's state. If the learner would not normally be able to see the exam content, an alert with this information will display for the masquerading user.
Related PRs:
https://github.com/edx/edx-platform/pull/28458
https://github.com/edx/frontend-app-learning/pull/610
---
---
=> fix: display exam content for masquerading user

src/exam/Exam.jsx, src/exam/ExamWrapper.test.jsx
The masquerading message for exams should only be shown if content is time gated, in addition to the other conditionals that were previously in place.
=> fix: only show masquerade message for time gated content

src/exam/Exam.jsx, src/exam/ExamWrapper.jsx, src/exam/ExamWrapper.test.jsx, src/instructions/proctored_exam/download-instructions/DefaultInstructions.jsx, src/instructions/proctored_exam/download-instructions/index.jsx
Handle content gating by allowing default learning MFE rendering instead of exam interstitials for sections that are locked. Note this behavior is distinctly different from the exam prerequisite views which are based solely on CreditRequirements. In the case both are not satisfied the effect of this PR is that content gating would take precedence. This is how the old LMS views currently work.
Bonus: Fixed some HTML validation that was barfing errors into the test console
@edx/masters-devs-cosmonauts
=> feat: support for content gating

src/timer/CountDownTimer.test.jsx, src/timer/TimerProvider.jsx
[MST-978 ](https://openedx.atlassian.net/browse/MST-978)
The special exam timer shown to learners should be updated with the exam attempt remaining time available for each sync interval. This is to ensure our learners don't see a timer which is running slower than the actual time.
Please review @edx/masters-devs-cosmonauts
=> [fix] The special exam timer synced with backend to show accurate count down timer

src/timer/CountDownTimer.test.jsx, src/timer/TimerProvider.jsx
This is a revert of a previous revert. This reverts commit e6aa31c100102235d04bd8d5507fc924a150719a. This PR would use the proper sermantic-release commit message.
The special exam timer shown to learners should be updated with the exam attempt remaining time available for each sync interval. This is to ensure our learners don't see a timer which is running slower than the actual time.
=> fix: The special exam timer synced with backend to show accurate count down timer

openedx.yaml
During the release process, the tag_release scripts crashes with:
```
Traceback (most recent call last):
File "/home/data/regis/projets/openedx/repos/repo-tools/.venv/bin/tag_release", line 33, in <module>
sys.exit(load_entry_point('edx-repo-tools', 'console_scripts', 'tag_release')())
File "/home/data/regis/projets/openedx/repos/repo-tools/.venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/home/data/regis/projets/openedx/repos/repo-tools/.venv/lib/python3.9/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/home/data/regis/projets/openedx/repos/repo-tools/.venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File …
```
=> fix: default branch is not "master"

src/constants.js, src/instructions/Instructions.test.jsx, src/instructions/index.jsx, src/instructions/proctored_exam/EntranceProctoredExamInstructions.jsx
Exam attempts that have been marked as ready to resume should remain resumable, even if they receive a review. This PR is the frontend portion to the changes made [to the backend](https://github.com/edx/edx-proctoring/pull/985), which transition the states of resuming from being represented as a status to being represented as a boolean field. As such, is is now possible for exam attempts to have an `error`, or any reviewed status, and also be marked as ready to resume. If the exam has been marked as ready to resume, we should prioritize that state over the current status.
=> fix: exam attempts marked as ready to resume should remain resumable

package-lock.json, package.json, src/exam/Exam.jsx, src/exam/ExamWrapper.jsx, src/instructions/Instructions.test.jsx, src/instructions/index.jsx
[MST-1150](https://openedx.atlassian.net/browse/MST-1150)
IDV is considered disabled for a course if the integrity signature flag is enabled. If this flag is turned on, do not block the learner from taking proctored exams if they do not have approved ID verification.
=> [MST-1150] Don't show IDV interstitial if IDV is disabled for the course

src/data/redux.test.jsx, src/data/thunks.js, src/instructions/Instructions.test.jsx, src/instructions/proctored_exam/ReadyToStartProctoredExamInstructions.jsx
1. The application will now wait 5 seconds to connect with the Proctortrack application before showing an error. This previously took two minutes with no user feedback what was happening.  Under the hood this will retry five times still.
2. Added a spinner to the button while this is taking place
3. Changed to the log level for these errors from info to error. Info messages don't seem to be getting logged, not sure why. Either way this should have no significant impact on error rates as we receive up to 600/hr for translation errors alone.
Note: This can be merged, but the timeout will still be two minutes until https://github.com/anupdhabarde/edx-proctoring-proctortrack/pull/19 is also merged
@edx/masters-devs-cosmonauts 
[MST-1252](https://openedx.atlassian.net/browse/MST-1252)
=> Improve Exam Start Failure

src/data/redux.test.jsx, src/data/thunks.js
The attempt object does not actually have an exam id on it so this was blowing up. Didn't get caught because we didn't have any testing on ping weirdly, now we do.
Also homogenized the log format between ping failures and start exam failures and included exam states so we can better differentiate in newrelic
=> fix: exam id logging

src/exam/ExamAPIError.jsx, src/exam/ExamAPIError.test.jsx, src/exam/__snapshots__/ExamAPIError.test.jsx.snap, src/exam/messages.js
https://openedx.atlassian.net/browse/MST-1266
Display the relevant error message more prominently, and fall back to a default message if there is none, or if the message is HTML. Also use the values defined in frontend config for site name + support URL, rather than relying on proctored exam settings.
Before
-------
After
-----
**Using the API error message:**
**Default message:**
=> [MST-1266] Improve API error messaging

src/exam/Exam.jsx, src/exam/ExamWrapper.test.jsx
This change fixes a bug associated with version 1.15.4 by [this PR](https://github.com/edx/frontend-lib-special-exams/pull/59).
The bug was that, the [code at frontend-lib-special-exam](https://github.com/edx/frontend-lib-special-exams/blob/main/src/exam/Exam.jsx#L61), which is part of the version 1.15.4, is excluding too much. When the content type is not of an exam type, the variable examType has the value "". I need to only check against an array of proctored exam types.
@edx/masters-devs-cosmonauts Please review
=> fix: only deny audit and honor code learners of certain exam types

package.json
The versions were so tightly defined, it made it hard for a consuming MFE to upgrade minor versions of other packages.
=> fix: ease peer dependency requirements to just major version

src/data/messages/handlers.js, src/data/slice.js, src/data/thunks.js
Supporting PR to: https://github.com/openedx/edx-proctoring/pull/1084
Take the external id from the exam attempt and pass it off to the JS worker
=> feat: pass external attempt id to provider js

jest.config.js, src/data/messages/handlers.js, src/data/thunks.js
Update frontend-lib to go along with https://github.com/openedx/edx-proctoring/pull/1106
edit: added an ignore to coverage to handlers.js since we don't have anything scaffolded out to test this.
=> feat: send attempt id on exam ping/end messages

.env.test, src/data/api.js, src/data/redux.test.jsx
If the exams service is configured, we should call `edx-exams` endpoints instead of `edx-proctoring`.
=> feat: call edx-exams if exams base url is defined

Makefile, babel.config.js, src/instructions/proctored_exam/SkipProctoredExamInstruction.jsx, src/timer/ExamTimerBlock.jsx
Multiple related changes:
- Fixed missing i18n directory when running `make extract_translations`
- Fixed jsx duplicate FormattedMessage IDs
- Refactored exam.examTimer.text into a single message instead of concatination
- Removed babel.config.js to fix missing i18n plugin which causes "No messages found" error
Refs: FC-0012 OEP-58
=> fix: i18n fixes and prep to push to Transifex

src/api.js, src/data/__factories__/examAccessToken.factory.js, src/data/__factories__/examState.factory.js, src/data/__factories__/index.js, src/data/__snapshots__/redux.test.jsx.snap, src/data/api.js, src/data/index.js, src/data/redux.test.jsx, src/data/slice.js, src/data/thunks.js, src/index.jsx
From the Jira ticket, [MST-1599](https://2u-internal.atlassian.net/browse/MST-1599): 
> Before the frontend-lib-special-exams can render any content within an exam, it should first fetch an access ticket. The access ticket will eventually be passed down to the xblock via cookie, but this ticket should only involve making a call to get the access ticket.
> 
> Prior to rendering any content (aka blocking rendering), the exams library should make a request to the get exam access ticket endpoint, and the endpoint will create a ticket and set it as a cookie.
=> feat: fetch exam access token

src/api.test.jsx, src/data/__snapshots__/redux.test.jsx.snap, src/data/api.js, src/data/redux.test.jsx, src/data/thunks.js, src/setupTest.js
Whenever an exam attempt endpoint is hit (create/update) this will first check if that exam has a property indicating it is managed by edx-proctoring instead of edx-exams. If so, route the request there.
When writing out tests for this I noticed that almost none of our test cases are running against a version of the app with EXAMS_BASE_URL set. Since that's the direction we're headed I've made that the default and added an extra test case to each thunk to validate the old integration is still working. I fixed a few issues with the existing tests but there's still work that could be done. This took a ton of lines because of how these tests are structured. A bigger refactor could eliminate o lot code in here but I didn't want to re-invent too many things at once so I stuck with the existing …
=> route attempt endpoints to correct backend

src/data/__snapshots__/redux.test.jsx.snap, src/data/api.js, src/data/redux.test.jsx, src/data/thunks.js
If the `EXAMS_BASE_URL` config settings is available, the frontend should call the exams service to retrieve provider related settings.
=> feat: update URL for provider settings

src/api.js, src/api.test.jsx
Part of [MST-1599](https://2u-internal.atlassian.net/browse/MST-1599).
Based on feedback from [this PR](https://github.com/openedx/frontend-app-learning/pull/1083) to fetch exam access token, we want to handle the null case when there is no exam. Thus the api functions here should include a null check to handle this.
=> feat: add null state check

src/data/api.js, src/data/redux.test.jsx, src/helpers.js, src/instructions/proctored_exam/ProctoredExamInstructions.test.jsx, src/instructions/proctored_exam/ReadyToStartProctoredExamInstructions.jsx, src/timer/CountDownTimer.jsx, src/timer/CountDownTimer.test.jsx, src/timer/ExamTimerBlock.jsx
With the movement of the "humanized time" logic to the frontend, `edx-exams` will only return the amount of total time left as an integer representing the amount of minutes left in an exam. Because of this change in backend behavior, the frontend now needs to humanize the total time if the data is being returned by `edx-exams`.
In order to accomplish this, I've refactored where the humanized time function is located so that is accessible for both the timer component and the API functions.
=> feat: update exam total time

src/instructions/Instructions.test.jsx, src/instructions/proctored_exam/download-instructions/LtiProviderInstructions.jsx, src/instructions/proctored_exam/download-instructions/RPNowInstructions.jsx, src/instructions/proctored_exam/download-instructions/RestProviderInstructions.jsx, src/instructions/proctored_exam/download-instructions/index.jsx
Adds a new interstitial for downloading/launching an LTI based proctoring tool. This is more or the the same content as the existing page but having a separate template will allow these instructions to deviate from what we have today as needed.
I did a bit of name refactoring to make it clear what download page is used in what case. 'Default' was a bit misleading because that UI is actually specific to RPNow.
=> feat: start lti proctoring software

src/data/slice.js, src/instructions/proctored_exam/ProctoredExamInstructions.test.jsx, src/instructions/proctored_exam/SubmitProctoredExamInstructions.jsx
If an exam attempt uses an LTI provider, start an LTI launch to end the assessment.
=> feat: add LTI launch for submitting exam

package-lock.json, package.json
Left out `frontend-platform` upgrade from dev dependencies, so also bump version there.
=> fix: bump peer dependency version for frontend-platform

src/instructions/Instructions.test.jsx, src/instructions/proctored_exam/download-instructions/index.jsx
Quick fix to unblock testing in stage. The update call for 'click_download_software' is always hitting edx-exams right now. I didn't replace this with the thunk which is what we probably should be doing long term. The way the thunk is written we'd end up making double calls to our latest attempt endpoint so it requires a bit more  refactoring to get there.
=> fix: missing legacy flag on download attempt call

src/data/messages/proctorio.js, src/data/redux.test.jsx, src/data/thunks.js
Waiting to merge until I confirm some details with Proctorio.
Add interface where we can send JS messages to the Proctorio browser application. This isn't ideal because it's an extra requirement beyond the LTI specification for proctored exam launches. However, this should't impact our certification as the edx platform does not rely on this message in any way.
=> feat: notify proctorio app of exam start

src/data/messages/proctorio.js, src/data/redux.test.jsx, src/data/thunks.js
To temporarily support exam submission for Proctorio, add a feature to end an exam via Proctorio's postMessage API
=> feat: add end_exam message for proctorio

src/data/__snapshots__/redux.test.jsx.snap, src/data/api.js, src/data/redux.test.jsx, src/instructions/proctored_exam/download-instructions/index.jsx
pair PR with https://github.com/edx/frontend-app-exams-dashboard/pull/11
The network call made by the download interstitial is a bit of a special snowflake it bypasses the thunk and calls the api directly. Added support to the existing 'poll' function to support requesting a specific exam by sequence id in this case.
=> fix: pollAttempt call on download page

src/timer/TimerProvider.jsx
This query string appears to just be some copy/paste from the old proctoring UI. It's not used for anything and causes the pollHandler to send failing requests if the attempt has no polling url. The cropped up after https://github.com/openedx/frontend-lib-special-exams/pull/113 was merged.
Tested manually. At the moment this component has no tests 😞
=> fix: timer polling url for LTI exams

src/data/messages/proctorio.js, src/data/redux.test.jsx, src/data/thunks.js, src/instructions/proctored_exam/ProctoredExamInstructions.test.jsx, src/instructions/proctored_exam/SubmitProctoredExamInstructions.jsx
- removes temporary window.postMessage for exam submission. The new proctoring app will use LTI
- update submission flow to use a single tab
This needs to get merged in conjunction with the new Proctorio extension so I'll hold merging until that goes out.
=> feat: use lti for exam end

src/data/thunks.js
Fixes a test failure in the learning MFE where the exam state was null. This is probably a good safety check to have anyway since this check runs on all subsections.
=> fix: exam state null check

src/data/messages/proctorio.js, src/data/redux.test.jsx
Fixes a bug in https://github.com/openedx/frontend-lib-special-exams/pull/116
The domain for this message should actually match the current page. This differs from the Proctorio docs a bit since they are customizing the domain on the extension to match the edX learning app.
=> fix: check app domain

src/instructions/proctored_exam/SubmitProctoredExamInstructions.jsx
Incorrect assumption that location.assign is a blocking call. This appears to cause submit() to possibly execute alongside the LTI redirect which would also submit the exam. There's still an issue with fully resolving the redirect to be solved but this issue is making it harder to debug.
=> fix: double submit race condition

src/data/messages/proctorio.js, src/data/redux.test.jsx
The proctorio extension running the exam will use a url on the exams service instead of the MFE url.
More details in https://github.com/edx/edx-exams/pull/227
=> feat: update checkApp origin requirement

src/data/__snapshots__/redux.test.jsx.snap, src/data/slice.js, src/instructions/Instructions.test.jsx, src/instructions/proctored_exam/download-instructions/LtiProviderInstructions.jsx, src/instructions/proctored_exam/download-instructions/index.jsx
**Jira:** [COSMO-130](https://2u-internal.atlassian.net/browse/COSMO-130)
**Dependencies:** https://github.com/edx/edx-exams/pull/231
This commit adds support for displaying a technical support URL for LTI-based providers on the download instructions interstitial. The download instructions will display a technical support URL when it is returned from the proctoring settings backend endpoint. If the technical support URL is not available, then the technical support email and technical support phone number will be used instead.
**supportURL**
**supportEmail, supportPhone**
**no supportURL, supportEmail, supportPhone**
=> feat: add support for a technical support URL in the LTI-based provider download instructions

src/exam/ExamWrapper.jsx, src/exam/ExamWrapper.test.jsx
Every sequence navigation renders a new ExamWrapper component causing us to hit the `/latest` endpoint every time. We really only need to do this in a few cases.
1. If the sequence is an exam itself
2. If we've first loaded the UI and there is an active exam in another sequence
If the store already has a latest exam there's no reason to keep checking it on every user navigation, the polling function will already take care of refreshing data. I expect this change to drastically reduce the number of API calls we're generating.
=> feat: reduce unnecessary api calls

src/core/OuterExamTimer.jsx, src/data/index.js, src/exam/Exam.jsx, src/timer/CountDownTimer.test.jsx, src/timer/ExamTimerBlock.jsx, src/timer/TimerProvider.jsx
**Jira**: [COSMO-174](https://2u-internal.atlassian.net/browse/COSMO-174)
* refactor: replace use of withExamStore higher-order component in TimerServiceProvider
* This commit replaces the use of the withExamStore higher-order component with the useDispatch and useSelector hooks in TimerServiceProvider.
* This commit also refactors components that use the TimerServiceProvider so that they no longer need to pass state and action creators via props. The TimerServiceProvider now gets whatever state it needs directly from the Redux store with a useSelector hook and imports and dispatches thunks directly by importing them from the data directory.
* The original pattern was to use the withExamStore higher-order component to provide context to the TimerServiceProvider and its children. This …
=> Refactor TimerServiceProvider to no longer use withExamStore higher-order-component.

src/api.js, src/api.test.jsx, src/core/OuterExamTimer.test.jsx, src/data/index.js, src/data/redux.test.jsx, src/exam/ExamAPIError.test.jsx, src/exam/ExamWrapper.test.jsx, src/index.jsx, src/instructions/Instructions.test.jsx, src/instructions/proctored_exam/ProctoredExamInstructions.test.jsx, src/setupTest.js, src/timer/CountDownTimer.test.jsx
**Jira**: [COSMO-175](https://2u-internal.atlassian.net/browse/COSMO-175)
* feat: refactor public API to use hooks instead of references to exported store
* This commit refactors the public API, used by the frontend-app-learning application to interact with the frontend-lib-special-exams state, to export a series of hooks. Originally, the public API imported the frontend-lib-special-exams store directly and operated on it in a series of exported functions. This posed a problem for our need to merge the frontend-app-learning and frontend-lib-special-exams stores, because the special exams store is initialized in this repository and used by public API. In order to eventually be able to remove the creation of the store in this repository, we have to remove references to the store by …
=> Refactor public API functions to no longer import and use store.

src/data/index.js, src/instructions/timed_exam/StartTimedExamInstructions.jsx, src/timer/ExamTimerBlock.jsx, src/timer/TimerProvider.jsx
There were a few things we missed in the refactoring that we caught during our first bug bash. These fixes ensure that an exam will be autosubmitted if the time runs out, and that an exam can be started.
=> fix: patch bugs found during bash

src/data/thunks.js
All thunks which result in a call to update an attempt status should account for whether or not the exam attempt is for a non-LTI provider. If the legacy status is not passed to the thunk, in this case `endExamWithFailure`, the frontend will only call `edx-exams`, which does not support routing PUT requests to update an attempt status back to `edx-proctoring`.
=> feat: pass legacy status of exam to failure thunk

src/data/__snapshots__/redux.test.jsx.snap, src/data/api.js, src/data/redux.test.jsx, src/data/thunks.js
Fix for https://2u-internal.atlassian.net/browse/COSMO-125
We seemed to forget to pass the sequenceId to the backend API call in thunks.js. I just added that back in, hopefully this should work on stage now.
=> fix: pass sequenceId to api call

src/core/OuterExamTimer.jsx, src/data/api.js, src/data/redux.test.jsx, src/data/thunks.js, src/timer/TimerProvider.jsx
Re-fix for: https://2u-internal.atlassian.net/browse/COSMO-125
- Combined fetchActiveAttempt &  fetchLatestExamAttempt into one function with an optional "sequenceId" variable. At the very least, this works without causing errors in non-exam-sequence views. Since the sequenceId is undefined in that case, due to the sequenceId needing to be extracted from the sequence page itself, we can at least still get the latest exam attempt data.
- To my best knowledge, we originally called for the attempt of an exam with a given sequenceId in order to get the latest attempt for an exam regardless of whether or not its active, such that the timer can be seen on non exam-sequence pages. However, we don't truly need the sequence_id for this.
- It's also possible that this was also designed this way so …
=> fix: workaround for pollAttempt fail in courseview

src/instructions/onboarding_exam/SubmittedOnboardingExamInstructions.jsx
A section of text in the submitted onboarding instructions was duplicated. I believe this may have been an oversight when copying over text for the instructions.
=> fix: remove duplicate language in onboarding instructions

src/data/redux.test.jsx, src/data/thunks.js, src/exam/ExamWrapper.jsx
1. Resolved issue where the exam entry check for the Proctoring software was not being executed. Seems like we missed a dispatch() call here when doing some redux refactoring a few months ago and this broke.
2. Fixes an edge case where if the backend moves to a terminated state in a way that isn't caused by a client error the frontend does not show the correct interstitial message.
2U-internal Issue: [COSMO-291](https://2u-internal.atlassian.net/browse/COSMO-291)
=> fix: correct exam entry check not called

src/data/thunks.js
Hidden code issue uncovered by #147 
This will error if the learner has no attempts on the exam section. ~I moved this line to a point where we've already checked that an exam attempt exists.~ Actually this is already checked earlier in the function, the value would always be false.
=> fix: null checking issue in exam entry

catalog-info.yml
https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055/decisions/0001-use-backstage-to-support-maintainers.html
=> docs: add catalog-info

src/instructions/Instructions.test.jsx, src/instructions/practice_exam/SubmittedPracticeExamInstructions.jsx, src/instructions/practice_exam/SubmittedPracticeExamInstructions.test.jsx
Ticket: [COSMO-512 🔒](https://2u-internal.atlassian.net/browse/COSMO-512)
After submitting a Practice Proctoring exam there's a "Retry my exam" that if clicked throws an Axios 400 error:
A Practice Proctoring exam that has an LTI provider cannot be retried. This update removes the button on such cases.
=> Remove retry button in LTI Proctorio exams

src/instructions/Instructions.test.jsx
Addressing a [comment that I forgot on a previous PR](https://github.com/openedx/frontend-lib-special-exams/pull/155#discussion_r1794129861). I've used the expression "legacy LTI exams" when it was meant to be "legacy proctoring exams".
=> Label correction on test

src/data/messages/handlers.js
TICKET: https://2u-internal.atlassian.net/browse/COSMO-637
Adds a "logError" that we will use to track failures when making request to the JS Worker for proctoring (i.e. with the Proctortrack software, as that's the only proctoring provider we use a JS Worker with).
=> chore: add logError for js worker call failures

package.json, src/exam/Exam.jsx
Fixes https://github.com/openedx/frontend-app-learning/issues/1695
Related PR: https://github.com/openedx/frontend-app-learning/pull/1724
This PR simply moves `<div className="d-flex flex-column justify-content-center"> ` from the Exam component. to the learning MFE.
Summary:
When content within a sequence is shorter than the height of the browser viewport, the .sequence-container > .outline-sidebar-wrapper element does not expand appropriately. This causes the course outline sidebar to be partially or completely hidden from view.
Steps to Reproduce:
Open a course sequence that contains very little content (e.g., a short paragraph or notice).
View the course in a tall browser window.
Observe that the sidebar navigation is cut off or hidden.
Expected Behavior:
The sidebar should remain …
=> fix: ensure full-height layout

src/exam/Exam.jsx, src/exam/ExamAPIError.jsx, src/instructions/proctored_exam/download-instructions/index.jsx, src/timer/CountDownTimer.jsx, src/timer/ExamTimerBlock.jsx
As part of the project for improvements as follow up of react-unit-test-utils, we are going to replace all usages of the deprecated `injectIntl` HOC with the `useIntl()` hook from @edx/frontend-platform/i18n. It is a very straight-forward change, in order to accomplish this we did the following changes:
- In components we have to remove the old `injectIntl`, remove intl as a prop and use the hook instead.
- On `src/timer/ExamTimerBlock.jsx` we got an error related to useEffect to not affect current functionality i just disabled the eslint rule on that line.
- On `src/timer/CountDownTimer.jsx` propTypes were missing so we added it since in this project is not using typescript yet.
Closes #166
=> Replace injectIntl with the useIntl() hook
